[package]
name = "arkbot"
version = "0.2.0-dev"
description = "A Rust rewrite (and complete redesign) of Arkanosis' Wikipedia bot"

authors = ["Jérémie Roquet <jroquet@arkanosis.net>"]

documentation = "https://github.com/Arkanosis/arkbot-rs"
homepage = "https://github.com/Arkanosis/arkbot-rs"
repository = "https://github.com/Arkanosis/arkbot-rs"

readme = "README.md"
license = "ISC"

keywords = ["wikipedia", "bot"]
categories = ["bot"]

edition = "2018"

[dependencies]
bzip2 = "0.4"
confy = "0.4"
docopt = "1.1"
quick-xml = "0.20"
regex = "1.4"
reqwest = { version = "0.10", features = ["blocking"] }
serde = "1.0"
serde_derive = "1.0"
